### ISSUE TITLE
No way to match on a subset of meta

### ISSUE THREAD

**Issue by mykecameron** [jsonapi-rb/jsonapi-rspec#10]
`have_meta` will only succeed on EXACT matches. Often I have shared examples that test for some omnipresent meta in responses across many endpoints (example, a UUID identifying the request which we use for debugging), but then some meta contents which are specific to a particular resource or API (example: pagination data for an index endpoint). 

We added a `contain_meta` matcher for this in our applications, happy to share back w/ a PR. 

Check out: https://github.com/jsonapi-rb/jsonapi-rspec/compare/master...mykecameron:add_partial_meta_matcher, I didn't want to open an unsolicited PR since its unclear to me what the best practices around contribution to this project are, or even if it is actively maintained. Any guidance would be appreciated!

**Comment by stas** [comment]
@mykecameron, apologies for the late reply.

I think it's better to make `have_meta` work as _contain_ rather than _equal_. I don't think we should introduce a new matcher just for this. Alternatively, let's add an option for the matcher to chain on exactly this behavior.

I'll be happy to take a look if you send a PR.
Thanks :bowing_man:

**Comment by stas** [comment]
Related #14 if somebody wants to pick it up :smiley:

**Comment by sa73917** [comment]
@stas - [something like this?](https://github.com/sa73917/jsonapi-rspec/commit/4609b515e0a8cac3e53b603c0691103ba3ee54cf) will make `have_meta` work as a _contain_ rather than an _equal_ with the exactly chain.  Though this does risk breaking people's existing tests who are expecting `have_meta` to be an exact match.

**Comment by stas** [comment]
@sa73917 yup, though the way you're checking for the subset could be a bit optimized, take a look at these sugestions (probably worth looking at the ruby v2.4+ compatibility though, so [`<=` operator](http://mruby.org/docs/api/Hash.html#%3C=-instance_method)  should be more than enough).

Thanks!

**Comment by sa73917** [comment]
Changed the subset logic as suggested [and raised a PR](https://github.com/jsonapi-rb/jsonapi-rspec/pull/22)

**Comment by stas** [comment]
Fixed in #22 thanks to @sa73917!
